from django.urls import path

from . import views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("upload/", views.upload_trace, name="upload_trace"),
    path("register/", views.register, name="register"),
    path("create/", views.trace_create, name="trace_create"),
    path("traces/", views.trace_list, name="trace_list"),
    path("traces/<uuid:trace_uuid>/", views.trace_detail, name="trace_detail"),
    path("traces/<int:pk>/delete/", views.delete_trace, name="delete_trace"),
    path("traces/<int:pk>/surfaces/", views.trace_surfaces, name="trace_surfaces"),
    path("about/", views.about, name="about"),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("admin-dashboard/premium/", views.admin_dashboard_premium, name="admin_dashboard_premium"),
    path("admin-dashboard/uploads/", views.admin_dashboard_uploads, name="admin_dashboard_uploads"),
    path("admin-dashboard/traces/", views.admin_dashboard_traces, name="admin_dashboard_traces"),
    path("admin-dashboard/workers/", views.admin_dashboard_workers, name="admin_dashboard_workers"),
    path("admin-dashboard/geozones/", views.admin_dashboard_geozones, name="admin_dashboard_geozones"),
    path(
        "admin-dashboard/geozones/<int:pk>/",
        views.admin_dashboard_geozone_detail,
        name="admin_dashboard_geozone_detail",
    ),
    path(
        "admin-dashboard/geozones/<int:pk>/toggle/",
        views.admin_dashboard_geozone_toggle,
        name="admin_dashboard_geozone_toggle",
    ),

    path("strava/activities/", views.strava_activities, name="strava_activities"),
    path("strava/import/", views.strava_import, name="strava_import"),
    path("pricing/", views.pricing, name="pricing"),
    path("stats/monthly/", views.stats_monthly, name="stats_monthly"),
    path("stats/traces/", views.stats_traces, name="stats_traces"),
    path("stats/badges/", views.stats_badges, name="stats_badges"),
    path("hexagons/<int:pk>/", views.hexagon_detail, name="hexagon_detail"),
    path("profile/", views.dashboard, name="profile"),
    path("settings/", views.settings, name="settings"),
    path("profile/badges/", views.badges, name="badges"),
    path("friends/", views.friends, name="friends"),
    path("api/hexagons/", views.landing_hexagons, name="landing_hexagons"),
    path("api/stats/monthly/", views.api_stats_monthly, name="api_stats_monthly"),
    path("api/stats/traces/", views.api_stats_traces, name="api_stats_traces"),
    path("api/traces/<uuid:trace_uuid>/status/", views.api_trace_status, name="api_trace_status"),
    path("api/upload/", views.api_upload_trace, name="api_upload_trace"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    path("leaderboard/surface/", views.cluster_leaderboard, name="cluster_leaderboard"),
    path("premium/", views.subscription_required, name="subscription_required"),
    path("subscriptions/", views.subscription_history, name="subscription_history"),
    path("s/<str:code>/", views.shared_profile, name="shared_profile"),
]
