# Generated by Django 6.0.3 on 2026-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("badge_awarded", "Badge awarded"),
                    ("friend_request", "Friend request"),
                    ("friend_accepted", "Friend accepted"),
                    ("trace_analyzed", "Trace analyzed"),
                    ("referral_signup", "Referral signup"),
                ],
                max_length=20,
            ),
        ),
    ]
