# Generated by Django 6.0.3 on 2026-03-05 16:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="route",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
