# Generated by Django 6.0.3 on 2026-03-05 17:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0002_trace_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedSurface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closed_surfaces",
                        to="traces.trace",
                    ),
                ),
            ],
        ),
    ]
