# Generated by Django 6.0.3 on 2026-03-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0003_closedsurface"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="extracted",
            field=models.BooleanField(default=False),
        ),
    ]
