# Generated by Django 6.0.3 on 2026-03-05 18:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0007_usersurfacestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersurfacestats",
            name="union",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                help_text="Union of all owned closed surfaces",
                null=True,
                srid=4326,
            ),
        ),
    ]
