# Generated by Django 6.0.3 on 2026-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0008_usersurfacestats_union"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="first_point_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
