# Generated by Django 6.0.3 on 2026-03-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0010_hexsurface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hexsurface",
            name="closed_surface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hexagons",
                to="traces.closedsurface",
            ),
        ),
    ]
