# Generated by Django 6.0.3 on 2026-03-09 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0011_alter_hexsurface_closed_surface"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HexSurface",
            new_name="Hexagon",
        ),
    ]
