# Generated by Django 6.0.3 on 2026-03-10 08:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0012_rename_hexsurface_to_hexagon"),
    ]

    operations = [
        migrations.AddField(
            model_name="closedsurface",
            name="segment_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trace",
            name="route",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
