# Generated by Django 6.0.3 on 2026-03-12 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0016_hexagonscore_remove_hexagon_owner_closed_surface"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trace",
            constraint=models.UniqueConstraint(
                fields=("uploaded_by", "first_point_date"),
                name="unique_trace_user_first_point_date",
            ),
        ),
    ]
