# Generated by Django 6.0.3 on 2026-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0017_unique_trace_user_first_point_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="hexagonscore",
            name="last_earned_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
