# Generated by Django 6.0.3 on 2026-03-12 20:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0018_hexagonscore_last_earned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersurfacestats",
            name="secret_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
