# Generated by Django 6.0.3 on 2026-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0021_add_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hexagonscore",
            name="last_earned_at",
            field=models.DateTimeField(),
        ),
    ]
