# Generated by Django 6.0.3 on 2026-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0026_userprofile_home_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatsrefresh",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
