# Generated by Django 6.0.3 on 2026-03-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0032_userbadge_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="hexagongainevent",
            name="is_first",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql="""\
WITH firsts AS (
    SELECT DISTINCT ON (hexagon_id, user_id) id
    FROM traces_hexagongainevent
    ORDER BY hexagon_id, user_id, earned_at
)
UPDATE traces_hexagongainevent
SET is_first = (id IN (SELECT id FROM firsts))
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
