# Generated by Django 6.0.3 on 2026-03-28 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0033_hexagongainevent_is_first"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="closedsurface",
            index=models.Index(fields=["owner"], name="closedsurface_owner"),
        ),
        migrations.AddIndex(
            model_name="hexagongainevent",
            index=models.Index(
                fields=["user", "earned_at"], name="hexagongainevent_user_earned"
            ),
        ),
        migrations.AddIndex(
            model_name="hexagonscore",
            index=models.Index(
                fields=["user", "points"], name="hexagonscore_user_points"
            ),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"], name="trace_user_uploaded_at"
            ),
        ),
    ]
