# Generated by Django 6.0.3 on 2026-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0034_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="status",
            field=models.CharField(
                choices=[("not_analyzed", "Not analyzed"), ("analyzed", "Analyzed")],
                default="not_analyzed",
                max_length=20,
            ),
        ),
    ]
