# Generated by Django 6.0.3 on 2026-03-29 12:20

from django.db import migrations


def set_existing_analyzed(apps, schema_editor):
    Trace = apps.get_model("traces", "Trace")
    Trace.objects.all().update(status="analyzed")


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0035_add_trace_status"),
    ]

    operations = [
        migrations.RunPython(set_existing_analyzed, migrations.RunPython.noop),
    ]
