# Generated by Django 6.0.3 on 2026-03-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0037_add_trace_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trace",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_analyzed", "Not analyzed"),
                    ("surface_extracted", "Surface extracted"),
                    ("analyzed", "Analyzed"),
                ],
                default="not_analyzed",
                max_length=20,
            ),
        ),
    ]
