# Generated by Django 6.0.3 on 2026-04-01 21:33

from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    Subscription = apps.get_model("traces", "Subscription")
    UserProfile = apps.get_model("traces", "UserProfile")
    today = timezone.now().date()
    active_user_ids = (
        Subscription.objects.filter(start_date__lte=today, end_date__gte=today)
        .values_list("user_id", flat=True)
        .distinct()
    )
    UserProfile.objects.filter(user_id__in=active_user_ids).update(is_premium=True)


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0042_alter_subscription_options_userprofile_is_premium_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
