# Generated by Django 6.0.3 on 2026-04-08 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0045_strava_import"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["to_user", "status"], name="friendship_to_status"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["from_user", "status"], name="friendship_from_status"
            ),
        ),
    ]
