# Generated by Django 6.0.4 on 2026-04-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0046_friendship_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_on_badge",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_friend",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_referral",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_trace_analyzed",
            field=models.BooleanField(default=True),
        ),
    ]
