# Generated by Django 6.0.4 on 2026-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traces", "0047_userprofile_email_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_on_challenge",
            field=models.BooleanField(default=True),
        ),
    ]
