# Generated by Django 6.0.3 on 2026-04-01 14:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("admin_level", models.PositiveSmallIntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("loaded_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="geozones.geozone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZoneLeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=150)),
                ("is_premium", models.BooleanField(default=False)),
                ("hexagons_conquered", models.PositiveIntegerField(default=0)),
                ("hexagons_acquired", models.PositiveIntegerField(default=0)),
                ("rank_conquered", models.PositiveIntegerField()),
                ("rank_acquired", models.PositiveIntegerField()),
                ("computed_at", models.DateTimeField()),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="geozones.geozone",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="geozone",
            index=models.Index(
                fields=["admin_level"], name="geozones_ge_admin_l_4be4ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoneleaderboardentry",
            index=models.Index(
                fields=["zone", "rank_conquered"], name="geozones_zo_zone_id_339830_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoneleaderboardentry",
            index=models.Index(
                fields=["zone", "rank_acquired"], name="geozones_zo_zone_id_869b70_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="zoneleaderboardentry",
            constraint=models.UniqueConstraint(
                fields=("zone", "user_id"), name="zone_leaderboard_zone_user_unique"
            ),
        ),
    ]
