# Generated by Django 6.0.3 on 2026-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geozones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geozone",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
