# Generated by Django 6.0.3 on 2026-04-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geozones", "0002_geozone_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geozone",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="geozone",
            constraint=models.UniqueConstraint(
                fields=("code",), name="geozone_code_unique"
            ),
        ),
    ]
