# Generated by Django 6.0.3 on 2026-04-05 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geozones", "0002_geozone_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyZoneRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=150)),
                ("is_premium", models.BooleanField(default=False)),
                ("hexagons_conquered", models.PositiveIntegerField(default=0)),
                ("hexagons_acquired", models.PositiveIntegerField(default=0)),
                ("rank_conquered", models.PositiveIntegerField()),
                ("rank_acquired", models.PositiveIntegerField()),
                ("computed_at", models.DateTimeField()),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_rankings",
                        to="geozones.geozone",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["zone", "period", "rank_conquered"],
                        name="geozones_mo_zone_id_75b0b0_idx",
                    ),
                    models.Index(
                        fields=["user_id", "rank_conquered"],
                        name="geozones_mo_user_id_f61fb0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zone", "period", "user_id"),
                        name="monthly_zone_ranking_unique",
                    )
                ],
            },
        ),
    ]
