# Generated by Django 6.0.3 on 2026-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geozones", "0003_alter_geozone_code_geozone_geozone_code_unique"),
        ("geozones", "0003_monthlyzoneranking"),
    ]

    operations = []
