# Generated by Django 6.0.3 on 2026-04-06 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geozones", "0003_monthlyzoneranking"),
        ("traces", "0045_strava_import"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("capture_hexagon", "Capture hexagon"),
                            ("max_points", "Max points"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capture_mode",
                    models.CharField(
                        blank=True,
                        choices=[("any", "Any (at least one)"), ("all", "All")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("premium_only", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geozone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="geozones.geozone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeHexagon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_hexagons",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "hexagon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_hexagons",
                        to="traces.hexagon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeLeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=150)),
                ("is_premium", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                ("rank", models.PositiveIntegerField()),
                ("computed_at", models.DateTimeField()),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="challenges.challenge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_threshold", models.PositiveIntegerField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("badge", "Badge"),
                            ("subscription_3m", "Subscription 3 months"),
                            ("subscription_6m", "Subscription 6 months"),
                            ("subscription_1y", "Subscription 1 year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("badge_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="challenges.challenge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="challenges/sponsors/"
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="challenges.challenge",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["start_date"], name="challenges__start_d_56bb4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["end_date"], name="challenges__end_dat_5dedbb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengehexagon",
            constraint=models.UniqueConstraint(
                fields=("challenge", "hexagon"), name="challenge_hexagon_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="challengeleaderboardentry",
            index=models.Index(
                fields=["challenge", "rank"], name="challenges__challen_6df869_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeleaderboardentry",
            constraint=models.UniqueConstraint(
                fields=("challenge", "user_id"), name="challenge_leaderboard_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeparticipant",
            constraint=models.UniqueConstraint(
                fields=("challenge", "user"), name="challenge_participant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengereward",
            constraint=models.UniqueConstraint(
                fields=("challenge", "rank_threshold", "reward_type"),
                name="challenge_reward_unique",
            ),
        ),
    ]
