# Generated by Django 6.0.3 on 2026-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="goal_threshold",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="hexagons_per_zone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="zone_admin_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challengeleaderboardentry",
            name="goal_met",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("capture_hexagon", "Capture hexagon"),
                    ("max_points", "Max points"),
                    ("active_days", "Active days"),
                    ("new_hexagons", "New hexagons"),
                    ("distinct_zones", "Distinct zones"),
                ],
                max_length=20,
            ),
        ),
    ]
