# Generated by Django 6.0.4 on 2026-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0005_widen_dataset_score_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("capture_hexagon", "Capture hexagon"),
                    ("max_points", "Max points"),
                    ("active_days", "Active days"),
                    ("new_hexagons", "New hexagons"),
                    ("distinct_zones", "Distinct zones"),
                    ("dataset_points", "Dataset points"),
                    ("visit_hexagons", "Visit hexagons"),
                ],
                max_length=20,
            ),
        ),
    ]
