# Generated by Django 6.0.4 on 2026-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_alter_challenge_challenge_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="challenge",
            name="rewards_awarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
