# Generated by Django 6.0.4 on 2026-04-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_add_is_visible_rewards_awarded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeparticipant",
            name="goal_met_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
