# Generated by Django 6.0.4 on 2026-04-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_add_is_visible_rewards_awarded_at"),
        ("traces", "0048_userprofile_email_on_challenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceChallengeContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_contributions",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_contributions",
                        to="traces.trace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trace"], name="challenges__trace_i_5a12bb_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trace", "challenge"),
                        name="unique_trace_challenge_contribution",
                    )
                ],
            },
        ),
    ]
