# Generated by Django 6.0.3 on 2026-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(unique=True)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("traces_uploaded", models.PositiveIntegerField(default=0)),
                ("total_distance_km", models.FloatField(default=0.0)),
                ("surfaces_detected", models.PositiveIntegerField(default=0)),
                ("hexagons_earned", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(unique=True)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("traces_uploaded", models.PositiveIntegerField(default=0)),
                ("total_distance_km", models.FloatField(default=0.0)),
                ("surfaces_detected", models.PositiveIntegerField(default=0)),
                ("hexagons_earned", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeeklyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(unique=True)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("traces_uploaded", models.PositiveIntegerField(default=0)),
                ("total_distance_km", models.FloatField(default=0.0)),
                ("surfaces_detected", models.PositiveIntegerField(default=0)),
                ("hexagons_earned", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YearlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(unique=True)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("traces_uploaded", models.PositiveIntegerField(default=0)),
                ("total_distance_km", models.FloatField(default=0.0)),
                ("surfaces_detected", models.PositiveIntegerField(default=0)),
                ("hexagons_earned", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
            },
        ),
    ]
