# Generated by Django 6.0.3 on 2026-03-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0002_rename_hexagons_earned_add_new_hexagons"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="monthlystats",
            constraint=models.CheckConstraint(
                condition=models.Q(("period__day", 1)),
                name="monthlystats_period_is_first_of_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklystats",
            constraint=models.CheckConstraint(
                condition=models.Q(("period__week_day", 2)),
                name="weeklystats_period_is_monday",
            ),
        ),
        migrations.AddConstraint(
            model_name="yearlystats",
            constraint=models.CheckConstraint(
                condition=models.Q(("period__day", 1), ("period__month", 1)),
                name="yearlystats_period_is_jan_first",
            ),
        ),
    ]
