# Generated by Django 6.0.3 on 2026-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0003_period_check_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("username", models.CharField(max_length=150)),
                ("hexagons_acquired", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "username"),
                        name="userdailystats_period_username",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserWeeklyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("username", models.CharField(max_length=150)),
                ("hexagons_acquired", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "username"),
                        name="userweeklystats_period_username",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period__week_day", 2)),
                        name="userweeklystats_period_is_monday",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserMonthlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("username", models.CharField(max_length=150)),
                ("hexagons_acquired", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "username"),
                        name="usermonthlystats_period_username",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period__day", 1)),
                        name="usermonthlystats_period_first_of_month",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserYearlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("username", models.CharField(max_length=150)),
                ("hexagons_acquired", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "username"),
                        name="useryearlystats_period_username",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period__day", 1), ("period__month", 1)),
                        name="useryearlystats_period_is_jan_first",
                    ),
                ],
            },
        ),
    ]
