# Generated by Django 6.0.3 on 2026-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0006_leaderboardentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDailyStats",
            fields=[
                ("period", models.DateField()),
                ("user_id", models.IntegerField()),
                ("hexagons_acquired", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "period",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.RenameIndex(
            model_name="leaderboardentry",
            new_name="statistics__rank_co_79b4a2_idx",
            old_name="statistics_l_rank_co_idx",
        ),
        migrations.RenameIndex(
            model_name="leaderboardentry",
            new_name="statistics__rank_ac_58af58_idx",
            old_name="statistics_l_rank_ac_idx",
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="rank_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="total_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["rank_points"], name="statistics__rank_po_51f9f7_idx"
            ),
        ),
    ]
