# Generated by Django 6.0.3 on 2026-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0007_userdailystats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardentry",
            name="rank_points",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="leaderboardentry",
            name="total_points",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
