# Generated by Django 6.0.3 on 2026-04-05 23:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0008_leaderboard_db_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterLeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=150)),
                ("is_premium", models.BooleanField(default=False)),
                ("largest_cluster_hex_count", models.PositiveIntegerField()),
                ("largest_cluster_area_m2", models.FloatField()),
                (
                    "largest_cluster_geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("computed_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["rank"], name="statistics__rank_e5dc98_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id",), name="cluster_leaderboard_user_unique"
                    )
                ],
            },
        ),
    ]
